apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"quintus"}}
  creationTimestamp: "2026-04-17T06:18:45Z"
  labels:
    kubernetes.io/metadata.name: quintus
  name: quintus
  resourceVersion: "550"
  uid: 6e12964b-29aa-42c0-a56c-318c2093d4ad
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
