apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"traefik","namespace":"quintus"}}
  creationTimestamp: "2026-04-17T06:18:45Z"
  name: traefik
  namespace: quintus
  resourceVersion: "553"
  uid: de2e9bac-e0d9-4bc4-a18a-f4baaba7a14d
