resources:
  - 00-namespace.yaml
  - 10-dex-configmap.yaml
  - 11-oauth2-proxy-secret.yaml
  - 12-queryexplorer-secrets.yaml
  - 13-queryexplorer-configmap.yaml
  - 20-dex-deployment.yaml
  - 21-dex-service.yaml
  - 30-oauth2-proxy-deployment.yaml
  - 31-oauth2-proxy-service.yaml
  - 40-traefik-serviceaccount.yaml
  - 41-traefik-clusterrole.yaml
  - 42-traefik-clusterrolebinding.yaml
  - 43-traefik-deployment.yaml
  - 44-traefik-service.yaml
  - 50-oauth-auth-middleware.yaml
  - 51-oauth-errors-middleware.yaml
  - 52-dex-ingressroute.yaml
  - 53-app-ingressroute.yaml
  - 60-queryexplorer-deployment.yaml
  - 61-queryexplorer-service.yaml
